#------------------------
# Add checks for sprint_1
#------------------------
#
# From Roadmap for sprint_1
# 1*. Create branch sprint_1 (already done)
# 2*. Create prototypes for messenger pages (or use template) (no work required)
# -3. Add Parcel to project
# 4. Configure PostCSS (or use preprocessor)
# 5. Add handlesbar to project (or use any other templating engine)
# 6. Develop messenger pages (from step 2)
# 7. Create clear structure, project must consist of modules
# 8. Configure Express
# 9. Use port 3000, use 'npm run start'
# 10. Add NodeJS version (>=12) to .nvmrc or package.json
# 11. Configure Netlify: use cloned github repository, add Netlify link to README.md, configure autodeploy from 'deploy' branch
# 12. Update README.md, add description of project
# 13*. Link Practicum account with GitHub (already done)
# 14*. Create Pull Request 'Sprint 1' from sprint_1 to main
# 15*. In main branch, add comment to README.md about opened PR from step 14

name: sprint1

on:
  push:
    branches:
      sprint_1
      
jobs:
  job_from_yandex_practicum:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get testing lib
      run: set -eu && git clone https://github.com/Yandex-Practicum/tests-second-floor.git
    - name: Check dist and node_modules in .gitignore
      run: bash tests-second-floor/sprint_1/check_gitignore.sh
    - name: (Roadmap 9) Check npm run start existence
      run: bash tests-second-floor/sprint_1/check_start.sh
    - name: (Roadmap 3) Check Parcel in start script
      run: bash tests-second-floor/sprint_1/check_parcel.sh
    #- name: (Roadmap 9) Check PORT 3000
    #  run: bash tests-second-floor/sprint_1/check_port.sh
    #- name: (Roadmap 9) Check routing
    #  run: node tests-second-floor/sprint_1/check_routing.js
      
